# Generated by Django 6.0.2 on 2026-03-10 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Entrollment',
            new_name='Enrollment',
        ),
        migrations.RenameField(
            model_name='instructor',
            old_name='departemant',
            new_name='department',
        ),
    ]
